- name: Change Gemfile
  hosts: your_target_host_or_group
  become: yes
  tasks:
    - name: Create Gemfile
      template:
        src: templates/Gemfile.j2
        dest: /home/ec2-user/raisetech-live8-sample-app/Gemfile
        owner: ec2-user
        group: ec2-user
        mode: '0664'

- name: bundle Run
  hosts: your_target_host_or_group
  become: no
  tasks:
    - name: bundle run
      command: ~/.rvm/gems/ruby-3.1.2/bin/bundle
      args:
        chdir: /home/ec2-user/raisetech-live8-sample-app

- name: Change spec_helper.rb
  hosts: your_target_host_or_group
  become: yes
  tasks:
    - name: Create spec_helper.rb
      template:
        src: templates/spec_helper.rb.j2
        dest: /home/ec2-user/raisetech-live8-sample-app/spec/spec_helper.rb
        owner: ec2-user
        group: ec2-user
        mode: '0664'

- name: Serverspec init automation
  hosts: your_target_host_or_group
  become: yes
  become_user: ec2-user
  vars:
    serverspec_dir: /home/ec2-user/my_serverspec_tests

  tasks:
    - name: Ensure serverspec directory exists
      file:
        path: "{{ serverspec_dir }}"
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Initialize serverspec
      expect:
        command: serverspec-init
        chdir: "{{ serverspec_dir }}"
        responses:
          (?i)Select number: '1'
          (?i)Vagrant instance y/n: 'y'
          (?i)Auto-configure Vagrant from Vagrantfile? y/n: 'y'

- name: RSpec Run
  hosts: your_target_host_or_group
  become: yes
  tasks:
    - name: rspec --init
      command: rspec --init
      args:
        chdir: /home/ec2-user/my_serverspec_tests
      become_user: ec2-user

- name: Change sample_spec.rb
  hosts: your_target_host_or_group
  become: yes
  tasks:
    - name: Create sample_spec.rb
      template:
        src: templates/sample_spec.rb.j2
        dest: /home/ec2-user/my_serverspec_tests/spec/sample_spec.rb
        owner: ec2-user
        group: ec2-user
        mode: '0664'